---
title: "Hofstede Cultural Value"
author: "JMJ"
date: "11/27/2020"
output: html_document
---

##Install the packages

```{r message=FALSE, warning=FALSE}
library(tidyverse) # upload the package
library(ggthemes)
library(readxl)
```

# Read cv file
```{r message=FALSE, warning=FALSE}
cv <- read_excel("6-dimensions-for-website-2015-12-08-0-100.xls")
class(cv)

summary(cv)
head(cv)
mean(cv$idv, na.rm = TRUE)
```

## Plot

```{r simple plot, message=FALSE, warning=FALSE}
plot(cv$idv, cv$pdi)

ggplot(data=cv, aes(x=idv, y=pdi)) +
  geom_point(size=5, col='red') +
  geom_smooth(method = lm) +
  theme_wsj()

```

```{r plot with labels, message=FALSE, warning=FALSE}

#install.packages("ggrepel")
library(ggrepel)
cv %>% 
  ggplot(aes(x=idv, y=pdi))+
  geom_point(size=3, color='red')+ #cheatsheet: https://rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf
  geom_smooth(method = lm) +
  geom_label_repel(aes(label=ctr))
```



## Regression
```{r simple regression, message=FALSE, warning=FALSE}
lm <- lm(pdi ~ idv, data = cv)
summary(lm)
```
# Correlation
```{r Correlations, message=FALSE, warning=FALSE}
#install.packages('GGally')
library(GGally)

ggpairs(cv, columns = c(4, 3, 5, 6, 7, 8))
help("ggpairs")

ggpairs(cv %>% select(idv, pdi, mas, uai, ltowvs, ivr))

ggcorr(cv %>% select(idv, pdi, mas, uai, ltowvs, ivr))

```
## Multiple Regression

```{r Multiple Regression, message=FALSE, warning=FALSE}

mlm <- lm(ivr ~ pdi + mas + uai + ltowvs + idv, data=cv)
mlm
summary(mlm)

```

